# Prometheus scrape configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics exported by the OTEL Collector
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
